name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Make
      run: apt-get update && apt-get install -y make

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: make build
      
    - name: Lint
      run: make lint
      
    - name: Test
      run: make test
